### ISSUE TITLE
When I try to compile main.py I get the error

### ISSUE THREAD

**Issue by ChuangHoward902** [bitraker/SteelSeriesScreenSync#2]
When I try to compile I get these errors:
2023-02-22 22:19:23 INFO     Starting application
2023-02-22 22:19:23 ERROR    Error when loading config: [Errno 2] No such file or directory: 'config.json'
2023-02-22 22:19:23 ERROR    Error when loading coreprops: [Errno 2] No such file or directory: ''
2023-02-22 22:19:23 ERROR    Error when registering game with SteelSeries API: 'NoneType' object is not subscriptable
2023-02-22 22:19:23 INFO     attempting to bind all devices
2023-02-22 22:19:23 ERROR    Error when binding keyboard: 'NoneType' object is not subscriptable
2023-02-22 22:19:23 INFO     removing keyboard binding
2023-02-22 22:19:23 ERROR    Error when binding mouse: 'NoneType' object is not subscriptable
2023-02-22 22:19:23 INFO     removing mouse binding
2023-02-22 22:19:23 ERROR    Error when binding pad top: 'NoneType' object is not subscriptable
2023-02-22 22:19:23 INFO     removing pad top binding
2023-02-22 22:19:23 ERROR    Error when binding pad bot: 'NoneType' object is not subscriptable
2023-02-22 22:19:23 INFO     removing pad bot binding
2023-02-22 22:19:23 WARNING  no devices are bound, attempting to remove app from SteelSeries and re-register
2023-02-22 22:19:23 ERROR    Error when removing game from SteelSeries API: 'NoneType' object is not subscriptable
2023-02-22 22:19:23 INFO     restarting ..
2023-02-22 22:19:23 INFO     relaxing SteelSeries API by waiting for 5 seconds
2023-02-22 22:19:41 ERROR    Error when registering game with SteelSeries API: 'NoneType' object is not subscriptable
2023-02-22 22:19:44 INFO     Starting application
2023-02-22 22:19:44 ERROR    Error when loading config: [Errno 2] No such file or directory: 'config.json'
2023-02-22 22:19:44 ERROR    Error when loading coreprops: [Errno 2] No such file or directory: ''
2023-02-22 22:19:44 ERROR    Error when registering game with SteelSeries API: 'NoneType' object is not subscriptable
2023-02-22 22:19:45 INFO     attempting to bind all devices
2023-02-22 22:19:45 ERROR    Error when binding keyboard: 'NoneType' object is not subscriptable
2023-02-22 22:19:45 INFO     removing keyboard binding
2023-02-22 22:19:45 ERROR    Error when binding mouse: 'NoneType' object is not subscriptable
2023-02-22 22:19:45 INFO     removing mouse binding
2023-02-22 22:19:45 ERROR    Error when binding pad top: 'NoneType' object is not subscriptable
2023-02-22 22:19:45 INFO     removing pad top binding
2023-02-22 22:19:45 ERROR    Error when binding pad bot: 'NoneType' object is not subscriptable
2023-02-22 22:19:45 INFO     removing pad bot binding
2023-02-22 22:19:45 WARNING  no devices are bound, attempting to remove app from SteelSeries and re-register
2023-02-22 22:19:45 ERROR    Error when removing game from SteelSeries API: 'NoneType' object is not subscriptable
2023-02-22 22:19:45 INFO     restarting ..
2023-02-22 22:19:45 INFO     relaxing SteelSeries API by waiting for 5 seconds
2023-02-22 22:21:32 ERROR    Error when registering game with SteelSeries API: 'NoneType' object is not subscriptable

**Comment by bitraker** [comment]
It seems like you are missing the config.json file from the directory where you have the main.py file. It is available in the repository here. Try and make sure the file is there and run it again. Let me know how it goes.

**Comment by ChuangHoward902** [comment]
There are no missing files in the folder, but the same problem still occurs when compiling

**Comment by bitraker** [comment]
Hmm.. It could be a pathing problem. It's definitely failing to find the coreProps path, which is essential to run. The code doesn't change dir to its directory when running, which could lead to pathing issues. 

Could you try and change directory into the same directory as the config.json file, before running?

This part of the code finds the file:
    def load_config(self):
        try:
            **with open("config.json", "r") as c:**
                config = json.loads(c.read())
                self.coreprops_path = config["coreprops_path"]
        except Exception as e:
            self.logger.error(f"Error when loading config: {e}")

This part is what is looking for the file. It could be written better, because it expects the current working directory to be where the config.json file is. 

If it fixes your issue, I can update the code to automatically switch dir.

If it doesn't post your steps, so I can reproduce it.

**Comment by howard0902** [comment]
The problem of config.json solved the problem of logo.ico in the same way, but it seems that there are new problems:
2023-02-23 22:25:06 INFO Starting application
2023-02-23 22:25:06 INFO attempting to bind all devices
Traceback (most recent call last):
   File "c:\Users\Howar\OneDrive\Desktop\SteelSeriesScreenSync-main\main.py", line 14, in <module>
     app.start()
   File "c:\Users\Howar\OneDrive\Desktop\SteelSeriesScreenSync-main\gui.py", line 391, in start
     self. update_gui()
   File "c:\Users\Howar\OneDrive\Desktop\SteelSeriesScreenSync-main\gui.py", line 357, in update_gui
     self.lbl_low_light.set_text(f"Low Light {self.screensync.tolerance}")
AttributeError: 'CTkLabel' object has no attribute 'set_text'

**Comment by ChuangHoward902** [comment]
The problem with conifg.json has been solved. Logo.ico has the same problem, but it seems that there are new problems:

2023-02-23 23:29:13 INFO Starting application
2023-02-23 23:29:13 INFO attempting to bind all devices
2023-02-23 23:29:13 INFO bind_keyboard succeeded
2023-02-23 23:29:13 INFO bind_mouse succeeded
2023-02-23 23:29:13 INFO bind_pad_top succeeded
2023-02-23 23:29:13 INFO bind_pad_bot succeeded
Traceback (most recent call last):
   File "c:\Users\Howar\OneDrive\Desktop\SteelSeriesScreenSync-main\main.py", line 14, in <module>
     app.start()
   File "c:\Users\Howar\OneDrive\Desktop\SteelSeriesScreenSync-main\gui.py", line 391, in start
     self. update_gui()
   File "c:\Users\Howar\OneDrive\Desktop\SteelSeriesScreenSync-main\gui.py", line 357, in update_gui
     self.lbl_low_light.set_text(f"Low Light {self.screensync.tolerance}")
AttributeError: 'CTkLabel' object has no attribute 'set_text'


At this point my keyboard responds, but only for 5 seconds



customtkinter version 5.1.2

**Comment by bitraker** [comment]
I was able to identify your issue. It's with the version of customtkinter. Their new API doesn't support the older versions.

You can fix it by uninstalling the new version and installing the version that this code was made with:

pip uninstall customtkinter
pip install customtkinter==3.11

**Comment by ChuangHoward902** [comment]
Thank you very much it works successfully now
